name: Windows-MSVC-CLANG

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release/**'
    tags:
      - '**'
  pull_request:
    types: [opened,synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ (github.head_ref && github.ref) || github.run_id }}
  cancel-in-progress: true

jobs:
  windows_ref:
    name: msvc/clang
    runs-on: [windows-latest]
    steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v3
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -T ClangCL -DBUILD_SHARED_LIBS=OFF -DGINKGO_BUILD_CUDA=OFF -DGINKGO_BUILD_OMP=OFF ..
        cmake --build . -j4 --config Release
        ctest . -C Release --output-on-failure
